### ISSUE TITLE
[docs] How does Tenkan work exactly?

### ISSUE THREAD

**Issue by corysimmons** [mojotech/stylus-redesign#3]
@kizu Can you clarify exactly where doc files, and Tenkan, need to be, and exactly what settings need to be set for Tenkan to read the appropriate branch?

Also, how does it work under the hood, and where does it put the output?

**Comment by kizu** [comment]
Tenkan is, actually, more like a library for Jekyll — https://github.com/kizu/tenkan/

However, what lies beyond the Stylus' site now is [Textyll](https://github.com/kizu/tenkan/) (which uses tenkan) — this is work-in-progress site/blog platform over Jekyll and using only things GitHub Pages is capable of (unlike octopress). It is in rather rough state, but it is already somewhat powerful, I managed to port the Stylus' site to it in, like, two hours maybe? To work on Stylus' site it is enough to fork the Stylus' `gh-pages` branch, do `git submodule update`, and then just run jekyll.

As it is just Jekyll, it puts its output in `_site`, but it is better to run it using `make serve` which would run a local server :)

**Comment by corysimmons** [comment]
Damn man, nice. I'll be picking your brain when I get around to https://github.com/corysimmons/gitdoc
