### ISSUE TITLE
Custom domain?

### ISSUE THREAD

**Issue by corysimmons** [mojotech/stylus-redesign#5]
http://stylus-lang.com and/or http://stylus.io are both available. I think these (especially the latter) are way easier to access than http://learnboost.github.io/stylus

I've been using Stylus for years and I still have to Google "Stylus" and click the first link everytime I need to get to the docs. :[

**Comment by thefoxis** [comment]
Where did you see stylus.io being available? I see it being taken. I see stylus-lang.com though. Didn't see any variations of stylus for short domain, so maybe we should go with the latter.

**Comment by corysimmons** [comment]
@thefoxis Ah, you're right about stylus.io. I just went to the site and it was dead. Yeah that sounds good (cheaper too).
